global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8081']
        labels:
          service: 'payment-service'

  - job_name: 'scheduling-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['scheduling-service:8082']
        labels:
          service: 'scheduling-service'

  - job_name: 'partner-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['partner-gateway:8083']
        labels:
          service: 'partner-gateway'

  - job_name: 'ledger-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ledger-service:8084']
        labels:
          service: 'ledger-service'

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']
        labels:
          service: 'kafka'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
